# Use root/example as user/password credentials
version: '3.1'

services:

  Snake-mongo:
    image: mongo
    container_name: SvSnakeMongo_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"

  Snake-mongo-express:
    image: mongo-express
    container_name: SvSnakeMongo_mongo-express
    restart: always
    depends_on:
      - Snake-mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@snake-mongo:27017/
      ME_CONFIG_BASICAUTH: false